### ISSUE TITLE
Image not loading in header 

### ISSUE THREAD

**Issue by rafwell** [fireguard/report#5]
Hi! When the html of header have an image, her not loading properly. I'm using `{{public_path('pathtomyimg.png')}}`. In the report body work fine.

**Comment by rafwell** [comment]
Outra coisa, você prefere que comunique em inglês ou português aqui? Meu inglês é meio sofrível, como já deve ter notado. kkkk

**Comment by meneguite** [comment]
Hi.. This problem I answered in a previous issue ( #3 ), at a glance and if you are not using the latest version at 0.1.7 update that your problem will be solved. If the problem still happens I will need more details to try to simulate the problem here.

PS.: @rafwell se possível gostaria de manter no inglês para que as issues ajudem outras pessoas que não dominam nosso idioma, mas se sentir desconfortável ou não conseguir expressar o que precisa em inglês fique a vontade para misturar com o Português que nos entendemos por aqui.. o importante é resolvermos o problema! :)

**Comment by rafwell** [comment]
Ok, no problem. I'm in the version 0.1.7. This is my html of header.blade.php:
```html
<style>	
	.header{
		display: inline-block;
		width: 100%;
		font-family: 'Open Sans', "Helvetica Neue", Helvetica, Arial, sans-serif;    
		font-size: 9px;
	}
	.header .logo{
		width: 100px;
		height: 60px;
		float: left;		
	}
	.header .logo img{
		max-width: 100%;
		max-height: 100%;
	}
	.header .empresa .nome{
		font-weight: bold;;
		font-size: 16px;
	}	
</style>
<html>
	<head>
		<meta charset="utf-8" />
	</head>
	<body>
		<div class="header">
			<div class="logo">
				<img src="{!!public_path('assets/img/logo.png')!!}">
			</div>
			<div class="empresa">
				<div class="nome">{{$Empresa->nome}}</div>
				<div class="endereco">{{$Empresa->endereco[0]->logradouro}}, {{$Empresa->endereco[0]->numero}}, {{$Empresa->endereco[0]->bairro}}</div>
				<div class="estado">{{$Empresa->endereco[0]->municipio->municipio}} - {{$Empresa->endereco[0]->uf}} - {{$Empresa->endereco[0]->cep}}</div>
				<div class="telefones">{{$Empresa->contato[0]->telefone}}/{{$Empresa->contato[0]->telefone2}}/{{$Empresa->contato[0]->celular}} - {{$Empresa->contato[0]->email}}</div>
			</div>
		</div>
	</body>
</html>
```

**Comment by meneguite** [comment]
To resolve this problem I suggest two possible solutions:

> **Replace public_path('assets/img/logo.png') with url('assets/img/logo.jpg')**
> Replace {!! public_path('assets/img/logo.png') !!} with file:///{!! public_path('assets/img/logo.jpg') !!}

**Comment by rafwell** [comment]
Hi!

> Replace public_path('assets/img/logo.png') with url('assets/img/logo.jpg')

Solved this issue. But, loading the image from url is most slow of then load directly from disk. Maybe that way is not best.
