### ISSUE TITLE
Low entropy for generated file names

### ISSUE THREAD

**Issue by carlosadrianosousa** [fireguard/report#9]
In the AbstractExporter.php, the method "setFileName($fileName)" sets the report file name based on the php function "sha1(time())", wich is a really weak function for generating unique file names.
The problem is that, if two users generates a report in a interval of a second, the same hash will be generated, making it possible for the fireguard to deliver a report different from the one initially requested (it also makes possible for a connection A to access the report data of a connection B).

A possible solution to this situation would be to increase the entropy of the generated hash by changing the line of code:

`$this->fileName = 'report-'.sha1(time());`

**To:**

`$this->fileName = 'report-'.sha1(uniqid(DB::connection()->getName(),true));`

**Comment by meneguite** [comment]
Hi, thank you very much for the feedback I will analyze this calmly and return soon.

**Comment by meneguite** [comment]
Hi @carlosadrianosousa, I just sent an update that increasing entropy for generated file names, unfortunately I can not use the example you sent because this package does not depend directly on laravel. But I believe that the solution adopted will meet with adequate reliability. Again thank you very much for the suggestion.
https://github.com/fireguard/report/releases/tag/v0.2.3

**Comment by carlosadrianosousa** [comment]
Thanks for the support.
You've made a really nice tool.
